export const HEALTH_CHECK_PORT = 'HEALTH_CHECK_PORT';
export const CHECK_HEALTH_USE_CASE = 'CHECK_HEALTH_USE_CASE';
export const CLIENTE_REPOSITORY = 'CLIENTE_REPOSITORY';
export const LIST_CLIENTES_USE_CASE = 'LIST_CLIENTES_USE_CASE';
export const GET_CLIENTE_USE_CASE = 'GET_CLIENTE_USE_CASE';
export const CREATE_CLIENTE_USE_CASE = 'CREATE_CLIENTE_USE_CASE';
export const UPDATE_CLIENTE_USE_CASE = 'UPDATE_CLIENTE_USE_CASE';
export const DELETE_CLIENTE_USE_CASE = 'DELETE_CLIENTE_USE_CASE';
