export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY';
export const LIST_CUSTOMERS_USE_CASE = 'LIST_CUSTOMERS_USE_CASE';
export const GET_CUSTOMER_USE_CASE = 'GET_CUSTOMER_USE_CASE';
export const CREATE_CUSTOMER_USE_CASE = 'CREATE_CUSTOMER_USE_CASE';
export const UPDATE_CUSTOMER_USE_CASE = 'UPDATE_CUSTOMER_USE_CASE';
export const DELETE_CUSTOMER_USE_CASE = 'DELETE_CUSTOMER_USE_CASE';
